@base_url = http://localhost:5071

Accept: application/json

### user Register
POST {{base_url}}/api/register
Content-Type: application/json

{
    "fullname": "shahidul",
    "email": "shahidul@gmail.com",
    "phone": "01712345679",
    "address": "Dhaka, Bangladesh",
    "password": "Password@123",
    "confirmPassword": "Password@123"
}

### login
POST {{base_url}}/api/login
Content-Type: application/json

{
    "UsernameOrEmailOrPhone":"shahidul@gmail.com",
    "Password":"Password@123"
}

### refresh-token
POST {{base_url}}/api/refresh-token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiM2IyMDUwNi00NGUxLTQ1YjctOTc2OS0yNDhkM2YyNzc2ZjIiLCJuYW1laWQiOiIwMWVkMzljMy0zYjZiLTRkNDEtYTVkMy03NmQ2MjIwOWMyNjciLCJ1bmlxdWVfbmFtZSI6InNoYWhpZHVsIiwiZnVsbE5hbWUiOiJzaGFoaWR1bCIsImVtYWlsIjoic2hhaGlkdWxAZ21haWwuY29tIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3OTA1OTQwODIsImV4cCI6MTc5MDU5NDM4MiwiaWF0IjoxNzkwNTk0MDgyLCJpc3MiOiJHU0V2ZW50IiwiYXVkIjoiVXNlciJ9.I-_rkt4waMjGOPrJ_yol0AL4AvSiibcKVRaqwvAMubY",
    "refreshToken" : "72IHsi+ytAhnsq7O3aEcMABWDJXcH6nmMWKZezYCVITpLD97UIAZVWEEDChu39rin5UJj9+Tl2vsQv6xH70qYg=="
}

### logout
POST {{base_url}}/api/logout
Content-Type: application/json

{
    "refreshToken": "VG9vtLV6xzPDAVuNuasYUzGT2HzE3U/pAVrNFEeralOrMWWVa8kQXLaiRnI1nSw9BgQMNMCfKh1ipV9cw2fUMQ=="
}

### Change password
POST {{base_url}}/api/change-password
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiM2IyMDUwNi00NGUxLTQ1YjctOTc2OS0yNDhkM2YyNzc2ZjIiLCJuYW1laWQiOiIwMWVkMzljMy0zYjZiLTRkNDEtYTVkMy03NmQ2MjIwOWMyNjciLCJ1bmlxdWVfbmFtZSI6InNoYWhpZHVsIiwiZnVsbE5hbWUiOiJzaGFoaWR1bCIsImVtYWlsIjoic2hhaGlkdWxAZ21haWwuY29tIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3OTA1OTQwODIsImV4cCI6MTc5MDU5NDM4MiwiaWF0IjoxNzkwNTk0MDgyLCJpc3MiOiJHU0V2ZW50IiwiYXVkIjoiVXNlciJ9.I-_rkt4waMjGOPrJ_yol0AL4AvSiibcKVRaqwvAMubY

{
    "OldPassword":"Password@123",
    "NewPassword":"new@1234678"
}
