@base_url = http://localhost:5071

Accept: application/json

### user Register
POST {{base_url}}/api/register
Content-Type: application/json

{
    "fullname": "shahidul",
    "email": "shahidul@gmail.com",
    "phone": "01712345679",
    "address": "Dhaka, Bangladesh",
    "password": "Password@123",
    "confirmPassword": "Password@123"
}

### login
POST {{base_url}}/api/login
Content-Type: application/json

{
    "UsernameOrEmailOrPhone":"shahidul@gmail.com",
    "Password":"Password@123"
}

### refresh-token
POST {{base_url}}/api/refresh-token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlODU2YzAxMC0wZWVhLTQ2ZWQtODg2MS00NjIxZWIyMTA5YWMiLCJuYW1laWQiOiIwMWVkMzljMy0zYjZiLTRkNDEtYTVkMy03NmQ2MjIwOWMyNjciLCJ1bmlxdWVfbmFtZSI6InNoYWhpZHVsIiwiZW1haWwiOiJzaGFoaWR1bEBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsIm5iZiI6MTc5MDQ5Nzc5OSwiZXhwIjoxNzkwNDk4MDk5LCJpYXQiOjE3OTA0OTc3OTksImlzcyI6IkdTRXZlbnQiLCJhdWQiOiJVc2VyIn0.05f0jjBzY4FGYTgLXq737lMNKKUIwQRmL1Op98OEKYw",
    "refreshToken" : "LIVh93912ie1y27VSOMF2x41HO9zOUCbb6/I2f8qPdiyuypPfiE8Oeh66z8j3aA9wpbOipbzYwSQRr5ha6mN0w=="
}

### logout
POST {{base_url}}/api/logout
Content-Type: application/json

{
    "refreshToken": "VG9vtLV6xzPDAVuNuasYUzGT2HzE3U/pAVrNFEeralOrMWWVa8kQXLaiRnI1nSw9BgQMNMCfKh1ipV9cw2fUMQ=="
}
